### ISSUE TITLE
Passing TlsConnector to the default Signaller

### ISSUE THREAD

**Issue by Hejsil** [centricular/webrtcsink-custom-signaller#1]
Hello. The default Signaller seems to mostly provide what we need, except for the ability to connect with at TlsConnector. I'd be happy to implement this myself and make a PR, but I wanted to ensure that this is actually a wanted feature.

I'm also not 100% sure how we would pass this none GObject struct to the signaller.

**Comment by Hejsil** [comment]
It seems the `Connector` in `async-tungstenite` depends on what `async-tls` you wonna use. Seems like that is not something we wonna pass to gobjects as a property. What we really only need is a way to pass the certificate to the Signaller, which should be a lot simpler

**Comment by MathieuDuponchelle** [comment]
Hey, did you mean to open this against webrtcsink itself? :)

Making the default signaller work over tls is definitely desirable, I'll be happy to review a PR.

The SignallableObject interface was designed with passing properties in mind fwiw: webrtcsink implements the `GstChildProxy` interface, which means the signaller object can be configured through it, for instance with gst-launch the address can be passed with: `gst-launch-1.0 webrtcsink signaller::address="ws://127.0.0.1:8443"`.

If you're not sure what API you want to add exactly, I'll ping Seb for his opinion on the webrtcsink issue when you've opened one :)

**Comment by Hejsil** [comment]
Aah, lol. Opened on the wrong repo indeed. I must have been browsing around just before opening this. Yea default signaller over tls exactly what I need. The question is just the exact API :)
